# Generated by Django 5.1 on 2025-05-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevOps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
