# Generated by Django 5.1 on 2025-05-23 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevOps', '0003_articlecolumn_articlepost_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='DevOps.articlecolumn'),
        ),
    ]
