# Generated by Django 5.1 on 2025-05-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevOps', '0005_articlepost_avatar_articlepost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
