# Generated by Django 5.1 on 2025-05-27 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DevOps', '0006_articlepost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepost',
            name='likes',
        ),
    ]
